services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - host
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:16.3-alpine3.20
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - host
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  host:
    driver: bridge

volumes:
  pg_data:
